# Theme
theme = "fleet_trans"

# Keys
[keys.normal]
g = { "left" = "goto_line_start", "right" = "goto_line_end" }
[keys.select]
g = { "left" = "goto_line_start", "right" = "goto_line_end" }

# Editor
[editor]
cursorline = true
true-color = true
color-modes = true
bufferline = "multiple"
line-number = "relative"
popup-border = "all"
end-of-line-diagnostics = "hint"
gutters = ["line-numbers", "diff", "diagnostics", "spacer"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "spacer",
  "version-control",
  "spacer",
  "diagnostics",
  "separator",
  "file-name",
  "file-modification-indicator",
]
right = [
  "spinner",
  "register",
  "spacer",
  "separator",
  "position",
  "position-percentage",
  "file-type",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
